---
title: "Quiz2"
author: "Jax Lubkowitz"
format: 
  html:
    embed-resources: true
---

Statement of Integrity: “All work presented is my own, and I have followed all rules for collaboration. I have not used any AI for this assignment.”
Jax Lubkowitz
# Question 1
```{r}
library(maps)
library(tidyverse)
library(here)
election_df <- read_csv(here("data/2020_county_pres.csv")) |>
  group_by(state_name) |>
  summarise(total_gop = sum(votes_gop),
            total_dem = sum(votes_dem)) |>
  mutate(percent_gop = 100 * total_gop / (total_gop + total_dem)) |>
  mutate(state_name = str_to_lower(state_name))

state_df <- ggplot2::map_data("state")

map_df <- left_join(state_df, election_df, by = c("region" = "state_name"))

ggplot(data = map_df, aes(x = long, y = lat, group = group)) +
  geom_polygon(colour = "black", aes(fill = percent_gop)) + # colored by coal variable
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  theme_void() +
  scale_fill_viridis_c(option = "plasma")
```

# Question 2
```{r}
statsurvey_df <- read_csv(here("data/stat113_survey.csv"))

statsurvey_df <- statsurvey_df |> 
  mutate(time_year = as.numeric(time_year)) |> 
  mutate(academic_year = if_else(time_semester == 's', true = time_year - 1, false = time_year )) |>
  filter(academic_year > 12) |> # all values before 2012 are NA so we can remove 
  mutate(Facebook = if_else(is.na(Facebook),
                               true = 0, false = Facebook)) 
  
# A.)
graph <- statsurvey_df |> 
  group_by(academic_year) |> 
  summarise(avg = mean(Facebook), total = n(), stdev = sd(Facebook)) |>
  mutate(se = stdev / sqrt(total), 
         lb_se = avg - se,
         ub_se = avg + se)

graph$academic_year <- factor(graph$academic_year)

ggplot(data = graph, aes(x = academic_year, y = avg)) +
  geom_col(color = "black", fill = "#E42B1C") +
  geom_errorbar(aes( ymin = lb_se, ymax = ub_se), width = .5, color = "black") +
  labs(y = "Avg # of Facebook Friends")

# B.)
graph2 <- statsurvey_df |> 
  mutate(has_facebook = if_else(Facebook == 0, true = 0, false = 1)) |>
  group_by(academic_year) |>
  mutate(total = n(),
         prop = mean(has_facebook),
         se = sqrt(prop*(1-prop)/total),
         ub_se = prop + se,
         lb_se = prop - se)

graph2$academic_year <- factor(graph2$academic_year)

ggplot(data = graph2, aes(x = academic_year, y = prop)) +
    geom_errorbar(aes( ymin = lb_se, ymax = ub_se), width = .25) +
    geom_point() +
    labs(y = "proportion of students with Facebook")

# C.)

statsurvey_partc <- statsurvey_df |> filter(GPA <= 4.0 & !is.na(Tattoo))

ggplot(data = statsurvey_partc, aes(x = Tattoo, y = GPA, ymin = 0, ymax = 4)) +
  geom_violin(color = "black",fill = "red") +
  theme_minimal() +
  labs(title = "Comparison of GPA in Students with and without Tatoos", subtitle = "Data is from Stat113 class at SLU", x = "Has Tatoo", y = "Grade Point Avg")
```


